version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  servicefrontend:
    build: ./serviceFrontEnd
    image: servicefrontend:latest
    ports:
      - "5001:5000" 
    depends_on:
      - redis

  servicea:
    build: ./serviceA
    image: servicea:latest
    depends_on:
      - redis

  serviceb:
    build: ./serviceB
    image: serviceb:latest
    depends_on:
      - redis

  servicecomplete:
    build: ./serviceComplete
    image: servicecomplete:latest
    depends_on:
      - redis
